version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: julianschooltime
      POSTGRES_PASSWORD: Pas$1234!
      POSTGRES_DB: todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  postgres_data:
